# Generated by Django 4.2.3 on 2024-01-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0003_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="category",
            field=models.CharField(
                choices=[
                    ("Sience fiction", "Sience Fiction"),
                    ("Drama", "Drama"),
                    ("Comedia", "Comedia"),
                    ("Sience", "Sience"),
                    ("Detective", "Detective"),
                    ("Medicine", "Medicine"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Published"),
                    ("not published", "Not Published"),
                    ("banned", "Banned"),
                ],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="text",
            field=models.TextField(max_length=10000),
        ),
    ]
